language: node_js
node_js:
- '14'
sudo: true
branches:
  only:
  - master
  - development
  - beta
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- sudo apt-get -y install expect
- pip install awscli --upgrade --user
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
- npm i -g npm@lts
- cd app
install:
- npm ci
- true
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - secure: $SECURE_KEY
  - secure: $SECURE_KEY
  - SENTRY_ORG=streamr
  - SENTRY_PROJECT=marketplace
  - OWNER=streamr
  - IMAGE_NAME=platform
import:
 - source: streamr-dev/travis-ci:aws-staging-secrets.yml@master
 - source: streamr-dev/travis-ci:aws-production-secrets.yml@master
 - source: streamr-dev/travis-ci:npm-secrets.yml@master
 - source: streamr-dev/travis-ci:docker-secrets.yml@master
jobs:
  include:
  - stage: Platform Tests
    if: type IN (pull_request)
    env:
    - DESCRIPTION=LINTER
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/linter.sh"
  - stage: Platform Tests
    if: type IN (pull_request)
    env:
    - DESCRIPTION=UNIT_TEST
    - STREAMR_API_URL=http://localhost/api/v1
    - STREAMR_WS_URL=ws://localhost/api/v1/ws
    - STREAMR_URL=http://localhost
    - PLATFORM_ORIGIN_URL=http://localhost
    script: "travis_retry $TRAVIS_BUILD_DIR/app/travis_scripts/unit-tests.sh"
    after_failure:
      - docker ps
      - $TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh log
  - stage: Platform tests
    if: type IN (pull_request)
    env:
    - DESCRIPTION=VISUAL_TEST
    - CHROMATIC_PROJECT_TOKEN=exgpyxh1il5
    - NODE_ENV=development
    - PORT=12345
    - VERSION=$TRAVIS_PULL_REQUEST_BRANCH
    - SENTRY_ENVIRONMENT=pr
    - STREAMR_API_URL=https://staging.streamr.com/api/v1
    - STREAMR_WS_URL=wss://staging.streamr.com/api/v1/ws
    - STREAMR_URL=https://staging.streamr.com
    - PLATFORM_ORIGIN_URL=https://staging.streamr.com
    - GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID
    - STORYBOOK_BASE_PATH=storybook
    - MARKETPLACE_CONTRACT_ADDRESS=0xA10151D088f6f2705a05d6c83719e99E079A61C1
    - DATA_TOKEN_CONTRACT_ADDRESS=0x0Cf0Ee63788A0849fE5297F3407f701E122cC023
    - DAI_TOKEN_CONTRACT_ADDRESS=0x6B175474E89094C44Da98b954EedeAC495271d0F
    - UNISWAP_ADAPTOR_CONTRACT_ADDRESS=0x0
    - WEB3_REQUIRED_NETWORK_ID=1
    - WEB3_PUBLIC_HTTP_PROVIDER=https://mainnet.infura.io/v3/17c3985baecb4c4d94a1edc2c4d23206
    - WEB3_PUBLIC_WS_PROVIDER=wss://mainnet.infura.io/ws/v3/17c3985baecb4c4d94a1edc2c4d23206
    - SENTRY_DSN=https://e012761929d24baa96ca82772f60b395@sentry.io/1203154
    - LOGROCKET_SLUG=et0uhu/streamr-frontend-local
    - DATA_UNION_PUBLISH_MEMBER_LIMIT=0
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/visual-tests.sh"
  - stage: Platform tests
    if: type IN (pull_request)
    env:
    - DESCRIPTION=END_TO_END_TEST
    - NODE_ENV=production
    - PORT=3333
    - STREAMR_URL=http://localhost
    - PLATFORM_ORIGIN_URL=http://localhost
    - STREAMR_API_URL=http://localhost/api/v1
    - STREAMR_WS_URL=ws://localhost/api/v1/ws
    - STREAMR_ENGINE_NODE_ADDRESSES=0xFCAd0B19bB29D4674531d6f115237E16AfCE377c
    - DATA_UNION_OPERATOR_ADDRESS=0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1
    - DATA_UNION_BLOCK_FREEZE_PERIOD_SECONDS=1
    - DATA_UNION_PUBLISH_MEMBER_LIMIT=1
    - MARKETPLACE_CONTRACT_ADDRESS=0xF1371c0f40528406dc4f4cAf89924eA9Da49E866
    - DATA_TOKEN_CONTRACT_ADDRESS=0xbAA81A0179015bE47Ad439566374F2Bae098686F
    - DAI_TOKEN_CONTRACT_ADDRESS=0x642d2b84a32a9a92fec78ceaa9488388b3704898
    - WEB3_REQUIRED_NETWORK_ID=8995
    - WEB3_PUBLIC_HTTP_PROVIDER=http://localhost:8545
    - WEB3_PUBLIC_WS_PROVIDER=ws://localhost:8545
    - WEB3_TRANSACTION_CONFIRMATION_BLOCKS=1
    - SENTRY_ORG=streamr
    - SENTRY_PROJECT=marketplace
    - UNISWAP_ADAPTOR_CONTRACT_ADDRESS=0xE4eA76e830a659282368cA2e7E4d18C4AE52D8B3
    - STORAGE_NODES="Local (broker-node-storage-1):0xde1112f631486CfC759A50196853011528bC5FA0"
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/e2e-tests.sh"
  - stage: Build docker (Dev/Nightly)
    if: branch = development
    env:
      - TAG=dev
    install: true
    script:
      - npm ci
      - npm run build-index
      - npm run build
      - docker build -t $OWNER/$IMAGE_NAME:local --build-arg NPM_TOKEN=${NPM_TOKEN} .
      - travis_scripts/smoke-test.sh
    after_failure:
      - docker ps
      - docker logs streamr_dev_platform
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash travis_scripts/deploy-docker.sh dev
        on:
          branch: development
  - stage: Build docker (Production)
    if: tag IS present AND branch = master
    env:
      - TAG=latest
    install: true
    script:
      - npm ci
      - npm run build-index
      - npm run build
      - docker build -t $OWNER/$IMAGE_NAME:local --build-arg NPM_TOKEN=${NPM_TOKEN} .
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash travis_scripts/deploy-docker.sh production
        on:
          branch: master
  - stage: Platform Build Staging
    if: NOT type IN (pull_request)
    env:
    - NODE_ENV=production
    - PORT=12345
    - VERSION=$TRAVIS_BRANCH
    - SENTRY_ENVIRONMENT=staging
    - BUNDLE_ANALYSIS=1
    - STREAMR_API_URL=https://staging.streamr.com/api/v1
    - STREAMR_WS_URL=wss://staging.streamr.com/api/v1/ws
    - PLATFORM_ORIGIN_URL=https://staging.streamr.com
    - STREAMR_URL=https://staging.streamr.com
    - PLATFORM_PUBLIC_PATH=https://marketplace-staging.streamr.com
    - GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID
    - STORYBOOK_BASE_PATH=storybook
    - MARKETPLACE_CONTRACT_ADDRESS=0x438229f341AEa22f18E69D98c2bE5997bc62d578
    - DATA_TOKEN_CONTRACT_ADDRESS=0x67a9fda28c4df570d1d5350acfa345194f4d4100
    - DAI_TOKEN_CONTRACT_ADDRESS=0x4CEed45382203e84d2eAB4A9F37D4F141e79A574
    - UNISWAP_ADAPTOR_CONTRACT_ADDRESS=0xE4d8C9d64404FE44cb44eb2a5886a07269E72bd6
    - WEB3_REQUIRED_NETWORK_ID=8995
    - WEB3_PUBLIC_HTTP_PROVIDER=https://staging.streamr.com:8540
    - WEB3_PUBLIC_WS_PROVIDER=wss://staging.streamr.com:8540/ws
    - SENTRY_DSN=https://e012761929d24baa96ca82772f60b395@sentry.io/1203154
    - LOGROCKET_SLUG=et0uhu/streamr-frontend-local
    - DATA_UNION_PUBLISH_MEMBER_LIMIT=0
    - STREAMR_ENGINE_NODE_ADDRESSES=0xFCAd0B19bB29D4674531d6f115237E16AfCE377c
    - DATA_UNION_OPERATOR_ADDRESS=0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1
    - DATA_UNION_BLOCK_FREEZE_PERIOD_SECONDS=1
    - WEB3_TRANSACTION_CONFIRMATION_BLOCKS=1
    - NO_TEST_HOOKS=1
    - STORAGE_NODES=$STREAMR_STORAGE_NODE_ADDRESS
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/build-app-stg.sh"
    deploy:
    - provider: s3
      access_key_id: $ACCESS_KEY_STG
      secret_access_key: $SECRET_ACCESS_KEY_STG
      bucket: eu-west-1-stg-streamr-marketplace
      local-dir: "$TRAVIS_BUILD_DIR/app/dist"
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        branch: development
    - provider: s3
      access_key_id: $ACCESS_KEY_STG
      secret_access_key: $SECRET_ACCESS_KEY_STG
      bucket: eu-west-1-stg-streamr-vault
      local-dir: "$TRAVIS_BUILD_DIR/build"
      upload-dir: marketplace/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        branch: development
    - provider: codedeploy
      access_key_id: $ACCESS_KEY_STG
      secret_access_key: $SECRET_ACCESS_KEY_STG
      bucket: eu-west-1-stg-streamr-vault
      key: $PROVIDER_KEY
      application: eu-west-1-stg-marketplace-codedeploy
      deployment_group: eu-west-1-stg-marketplace-deployment-group
      region: eu-west-1
      on:
        branch: development
  - stage: Deploy Pull Request
    if: type IN (pull_request)
    env:
    - NODE_ENV=production
    - PORT=12345
    - VERSION=$TRAVIS_PULL_REQUEST_BRANCH
    - SENTRY_ENVIRONMENT=pr
    - BUNDLE_ANALYSIS=1
    - STREAMR_API_URL=https://staging.streamr.com/api/v1
    - STREAMR_WS_URL=wss://staging.streamr.com/api/v1/ws
    - PLATFORM_ORIGIN_URL=https://staging.streamr.com
    - STREAMR_URL=https://staging.streamr.com
    - PLATFORM_PUBLIC_PATH=https://streamr-marketplace-pr-$TRAVIS_PULL_REQUEST_SHA.s3-eu-west-1.amazonaws.com
    - GOOGLE_ANALYTICS_ID=55331565-5
    - STORYBOOK_BASE_PATH=storybook
    - MARKETPLACE_CONTRACT_ADDRESS=0x438229f341AEa22f18E69D98c2bE5997bc62d578
    - DATA_TOKEN_CONTRACT_ADDRESS=0x67a9fda28c4df570d1d5350acfa345194f4d4100
    - DAI_TOKEN_CONTRACT_ADDRESS=0x4CEed45382203e84d2eAB4A9F37D4F141e79A574
    - UNISWAP_ADAPTOR_CONTRACT_ADDRESS=0xE4d8C9d64404FE44cb44eb2a5886a07269E72bd6
    - WEB3_REQUIRED_NETWORK_ID=8995
    - WEB3_PUBLIC_HTTP_PROVIDER=https://staging.streamr.com:8540
    - WEB3_PUBLIC_WS_PROVIDER=wss://staging.streamr.com:8540/ws
    - SENTRY_DSN=https://e012761929d24baa96ca82772f60b395@sentry.io/1203154
    - LOGROCKET_SLUG=et0uhu/streamr-frontend-local
    - DATA_UNION_PUBLISH_MEMBER_LIMIT=0
    - STREAMR_ENGINE_NODE_ADDRESSES=0xFCAd0B19bB29D4674531d6f115237E16AfCE377c
    - DATA_UNION_OPERATOR_ADDRESS=0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1
    - DATA_UNION_BLOCK_FREEZE_PERIOD_SECONDS=1
    - WEB3_TRANSACTION_CONFIRMATION_BLOCKS=1
    - NO_TEST_HOOKS=1
    - STORAGE_NODES=$STREAMR_STORAGE_NODE_ADDRESS
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/deploy-pr.sh"
  - stage: Platform Build Production
    if: NOT type IN (pull_request)
    env:
    - NODE_ENV=production
    - VERSION=$TRAVIS_TAG
    - PORT=12345
    - VERSION=$TRAVIS_TAG
    - SENTRY_ENVIRONMENT=production
    - STREAMR_API_URL=https://streamr.network/api/v1
    - STREAMR_WS_URL=wss://streamr.network/api/v1/ws
    - PLATFORM_ORIGIN_URL=https://streamr.network
    - PLATFORM_PUBLIC_PATH=https://cdn.streamr.com
    - STREAMR_URL=https://streamr.network
    - GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID
    - MARKETPLACE_CONTRACT_ADDRESS=0x2b3F2887c697B3f4f8D9F818c95482e1a3A759A5
    - DATA_TOKEN_CONTRACT_ADDRESS=0x0Cf0Ee63788A0849fE5297F3407f701E122cC023
    - DAI_TOKEN_CONTRACT_ADDRESS=0x6B175474E89094C44Da98b954EedeAC495271d0F
    - UNISWAP_ADAPTOR_CONTRACT_ADDRESS=0xBe99DB4Ea1964ea9A9E80de41517901Da6ef9307
    - WEB3_REQUIRED_NETWORK_ID=1
    - WEB3_PUBLIC_HTTP_PROVIDER=https://mainnet.infura.io/v3/17c3985baecb4c4d94a1edc2c4d23206
    - WEB3_PUBLIC_WS_PROVIDER=wss://mainnet.infura.io/ws/v3/17c3985baecb4c4d94a1edc2c4d23206
    - SENTRY_DSN=https://e012761929d24baa96ca82772f60b395@sentry.io/1203154
    - STREAMR_ENGINE_NODE_ADDRESSES=0xf3E5A65851C3779f468c9EcB32E6f25D9D68601a
    - DATA_UNION_OPERATOR_ADDRESS=0xc0aa4dC0763550161a6B59fa430361b5a26df28C
    - DATA_UNION_BLOCK_FREEZE_PERIOD_SECONDS=1
    - DATA_UNION_PUBLISH_MEMBER_LIMIT=1
    - WEB3_TRANSACTION_CONFIRMATION_BLOCKS=1
    - AWS_ACCESS_KEY_ID=$ACCESS_KEY_PRD
    - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY_PRD
    - NO_TEST_HOOKS=1
    - STORAGE_NODES=$STREAMR_STORAGE_NODE_ADDRESS
    script: "$TRAVIS_BUILD_DIR/app/travis_scripts/build-app.sh"
    deploy:
    - provider: s3
      access_key_id: $ACCESS_KEY_PRD
      secret_access_key: $SECRET_ACCESS_KEY_PRD
      bucket: eu-west-1-streamr-cdn
      local-dir: "$TRAVIS_BUILD_DIR/app/dist"
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: true
    - provider: s3
      access_key_id: $ACCESS_KEY_PRD
      secret_access_key: $SECRET_ACCESS_KEY_PRD
      bucket: eu-west-1-streamr-vault
      local-dir: "$TRAVIS_BUILD_DIR/app/dist"
      upload-dir: marketplace/releases/latest
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: false
    - provider: s3
      access_key_id: $ACCESS_KEY_PRD
      secret_access_key: $SECRET_ACCESS_KEY_PRD
      bucket: eu-west-1-streamr-vault
      local-dir: "$TRAVIS_BUILD_DIR/app/dist"
      upload-dir: marketplace/releases/$TRAVIS_TAG
      acl: private
      region: eu-west-1
      skip_cleanup: true
      on:
        tags: true
    - provider: script
      script:
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
      on:
        tags: true
notifications:
  slack:
    secure: $SLACK_KEY
  if: branch = master
  on_success: change
  on_failure: always
  on_pull_requests: false
